import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';
import linkedin from 'react-linkedin-login-oauth2/assets/linkedin.png';
import { useLinkedIn } from 'react-linkedin-login-oauth2';

export default function Home() {
  const [code, setCode] = useState('');
  const [errorMessage, setErrorMessage] = useState('');

  const { linkedInLogin } = useLinkedIn({
    clientId: '86vhj2q7ukf83q',
    redirectUri: `${
      typeof window === 'object' && window.location.origin
    }/linkedin`,
    onSuccess: (code) => {
      console.log(code);
      setCode(code);
    },
    scope: 'r_emailaddress',
    onError: (error) => {
      console.log(error);
      setErrorMessage(error.errorMessage);
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
          <Image
            src={linkedin}
            alt="Log in with Linked In"
            width={180}
            height={32}
            onClick={linkedInLogin}
          />
          {!code && <div>No code</div>}
          {code && <div>Code: {code}</div>}
          {errorMessage && <div>{errorMessage}</div>}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
